/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetAccountAgreements200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccountAgreements200Response{}

// GetAccountAgreements200Response Acknowledgment status for agreements on your account. When acknowledging any agreements, set them to `true` and omit any remainders.
type GetAccountAgreements200Response struct {
	// The acknowledgement status for the [cross-border data transfer](https://www.akamai.com/legal/compliance/privacy-trust-center/cross-border-data-transfer-statement) agreement.
	EuModel *bool `json:"eu_model,omitempty"`
	// The acknowledgement status for Akamai's [master service agreement](https://www.linode.com/legal-msa/).
	MasterServiceAgreement *bool `json:"master_service_agreement,omitempty"`
	// The acknowledgement status for Akamai's [privacy statement](https://www.akamai.com/legal/privacy-statement).
	PrivacyPolicy *bool `json:"privacy_policy,omitempty"`
}

// NewGetAccountAgreements200Response instantiates a new GetAccountAgreements200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountAgreements200Response() *GetAccountAgreements200Response {
	this := GetAccountAgreements200Response{}
	return &this
}

// NewGetAccountAgreements200ResponseWithDefaults instantiates a new GetAccountAgreements200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountAgreements200ResponseWithDefaults() *GetAccountAgreements200Response {
	this := GetAccountAgreements200Response{}
	return &this
}

// GetEuModel returns the EuModel field value if set, zero value otherwise.
func (o *GetAccountAgreements200Response) GetEuModel() bool {
	if o == nil || IsNil(o.EuModel) {
		var ret bool
		return ret
	}
	return *o.EuModel
}

// GetEuModelOk returns a tuple with the EuModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountAgreements200Response) GetEuModelOk() (*bool, bool) {
	if o == nil || IsNil(o.EuModel) {
		return nil, false
	}
	return o.EuModel, true
}

// HasEuModel returns a boolean if a field has been set.
func (o *GetAccountAgreements200Response) HasEuModel() bool {
	if o != nil && !IsNil(o.EuModel) {
		return true
	}

	return false
}

// SetEuModel gets a reference to the given bool and assigns it to the EuModel field.
func (o *GetAccountAgreements200Response) SetEuModel(v bool) {
	o.EuModel = &v
}

// GetMasterServiceAgreement returns the MasterServiceAgreement field value if set, zero value otherwise.
func (o *GetAccountAgreements200Response) GetMasterServiceAgreement() bool {
	if o == nil || IsNil(o.MasterServiceAgreement) {
		var ret bool
		return ret
	}
	return *o.MasterServiceAgreement
}

// GetMasterServiceAgreementOk returns a tuple with the MasterServiceAgreement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountAgreements200Response) GetMasterServiceAgreementOk() (*bool, bool) {
	if o == nil || IsNil(o.MasterServiceAgreement) {
		return nil, false
	}
	return o.MasterServiceAgreement, true
}

// HasMasterServiceAgreement returns a boolean if a field has been set.
func (o *GetAccountAgreements200Response) HasMasterServiceAgreement() bool {
	if o != nil && !IsNil(o.MasterServiceAgreement) {
		return true
	}

	return false
}

// SetMasterServiceAgreement gets a reference to the given bool and assigns it to the MasterServiceAgreement field.
func (o *GetAccountAgreements200Response) SetMasterServiceAgreement(v bool) {
	o.MasterServiceAgreement = &v
}

// GetPrivacyPolicy returns the PrivacyPolicy field value if set, zero value otherwise.
func (o *GetAccountAgreements200Response) GetPrivacyPolicy() bool {
	if o == nil || IsNil(o.PrivacyPolicy) {
		var ret bool
		return ret
	}
	return *o.PrivacyPolicy
}

// GetPrivacyPolicyOk returns a tuple with the PrivacyPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountAgreements200Response) GetPrivacyPolicyOk() (*bool, bool) {
	if o == nil || IsNil(o.PrivacyPolicy) {
		return nil, false
	}
	return o.PrivacyPolicy, true
}

// HasPrivacyPolicy returns a boolean if a field has been set.
func (o *GetAccountAgreements200Response) HasPrivacyPolicy() bool {
	if o != nil && !IsNil(o.PrivacyPolicy) {
		return true
	}

	return false
}

// SetPrivacyPolicy gets a reference to the given bool and assigns it to the PrivacyPolicy field.
func (o *GetAccountAgreements200Response) SetPrivacyPolicy(v bool) {
	o.PrivacyPolicy = &v
}

func (o GetAccountAgreements200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAccountAgreements200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EuModel) {
		toSerialize["eu_model"] = o.EuModel
	}
	if !IsNil(o.MasterServiceAgreement) {
		toSerialize["master_service_agreement"] = o.MasterServiceAgreement
	}
	if !IsNil(o.PrivacyPolicy) {
		toSerialize["privacy_policy"] = o.PrivacyPolicy
	}
	return toSerialize, nil
}

type NullableGetAccountAgreements200Response struct {
	value *GetAccountAgreements200Response
	isSet bool
}

func (v NullableGetAccountAgreements200Response) Get() *GetAccountAgreements200Response {
	return v.value
}

func (v *NullableGetAccountAgreements200Response) Set(val *GetAccountAgreements200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountAgreements200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountAgreements200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountAgreements200Response(val *GetAccountAgreements200Response) *NullableGetAccountAgreements200Response {
	return &NullableGetAccountAgreements200Response{value: val, isSet: true}
}

func (v NullableGetAccountAgreements200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountAgreements200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


