/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEntityTransfers200ResponseAllOfDataInnerEntities type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEntityTransfers200ResponseAllOfDataInnerEntities{}

// GetEntityTransfers200ResponseAllOfDataInnerEntities A collection of the entities to include in this transfer request, separated by type.
type GetEntityTransfers200ResponseAllOfDataInnerEntities struct {
	// An array containing the IDs of each of the Linodes included in this transfer.
	Linodes []int32 `json:"linodes,omitempty"`
}

// NewGetEntityTransfers200ResponseAllOfDataInnerEntities instantiates a new GetEntityTransfers200ResponseAllOfDataInnerEntities object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEntityTransfers200ResponseAllOfDataInnerEntities() *GetEntityTransfers200ResponseAllOfDataInnerEntities {
	this := GetEntityTransfers200ResponseAllOfDataInnerEntities{}
	return &this
}

// NewGetEntityTransfers200ResponseAllOfDataInnerEntitiesWithDefaults instantiates a new GetEntityTransfers200ResponseAllOfDataInnerEntities object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEntityTransfers200ResponseAllOfDataInnerEntitiesWithDefaults() *GetEntityTransfers200ResponseAllOfDataInnerEntities {
	this := GetEntityTransfers200ResponseAllOfDataInnerEntities{}
	return &this
}

// GetLinodes returns the Linodes field value if set, zero value otherwise.
func (o *GetEntityTransfers200ResponseAllOfDataInnerEntities) GetLinodes() []int32 {
	if o == nil || IsNil(o.Linodes) {
		var ret []int32
		return ret
	}
	return o.Linodes
}

// GetLinodesOk returns a tuple with the Linodes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntityTransfers200ResponseAllOfDataInnerEntities) GetLinodesOk() ([]int32, bool) {
	if o == nil || IsNil(o.Linodes) {
		return nil, false
	}
	return o.Linodes, true
}

// HasLinodes returns a boolean if a field has been set.
func (o *GetEntityTransfers200ResponseAllOfDataInnerEntities) HasLinodes() bool {
	if o != nil && !IsNil(o.Linodes) {
		return true
	}

	return false
}

// SetLinodes gets a reference to the given []int32 and assigns it to the Linodes field.
func (o *GetEntityTransfers200ResponseAllOfDataInnerEntities) SetLinodes(v []int32) {
	o.Linodes = v
}

func (o GetEntityTransfers200ResponseAllOfDataInnerEntities) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEntityTransfers200ResponseAllOfDataInnerEntities) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Linodes) {
		toSerialize["linodes"] = o.Linodes
	}
	return toSerialize, nil
}

type NullableGetEntityTransfers200ResponseAllOfDataInnerEntities struct {
	value *GetEntityTransfers200ResponseAllOfDataInnerEntities
	isSet bool
}

func (v NullableGetEntityTransfers200ResponseAllOfDataInnerEntities) Get() *GetEntityTransfers200ResponseAllOfDataInnerEntities {
	return v.value
}

func (v *NullableGetEntityTransfers200ResponseAllOfDataInnerEntities) Set(val *GetEntityTransfers200ResponseAllOfDataInnerEntities) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEntityTransfers200ResponseAllOfDataInnerEntities) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEntityTransfers200ResponseAllOfDataInnerEntities) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEntityTransfers200ResponseAllOfDataInnerEntities(val *GetEntityTransfers200ResponseAllOfDataInnerEntities) *NullableGetEntityTransfers200ResponseAllOfDataInnerEntities {
	return &NullableGetEntityTransfers200ResponseAllOfDataInnerEntities{value: val, isSet: true}
}

func (v NullableGetEntityTransfers200ResponseAllOfDataInnerEntities) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEntityTransfers200ResponseAllOfDataInnerEntities) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


