/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice{}

// GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice The default cost of enabling Backups for this Linode Type. Prices are in US dollars, broken down into hourly and monthly charges.  Certain regions have different prices from the default. For region-specific prices, see `region_prices`.
type GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice struct {
	// The cost (in US dollars) per hour to add Backups service.
	Hourly *float32 `json:"hourly,omitempty"`
	// The cost (in US dollars) per month to add Backups service.
	Monthly *float32 `json:"monthly,omitempty"`
}

// NewGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice instantiates a new GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice() *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice {
	this := GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice{}
	return &this
}

// NewGetLinodeTypes200ResponseDataInnerAddonsBackupsPriceWithDefaults instantiates a new GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLinodeTypes200ResponseDataInnerAddonsBackupsPriceWithDefaults() *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice {
	this := GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice{}
	return &this
}

// GetHourly returns the Hourly field value if set, zero value otherwise.
func (o *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) GetHourly() float32 {
	if o == nil || IsNil(o.Hourly) {
		var ret float32
		return ret
	}
	return *o.Hourly
}

// GetHourlyOk returns a tuple with the Hourly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) GetHourlyOk() (*float32, bool) {
	if o == nil || IsNil(o.Hourly) {
		return nil, false
	}
	return o.Hourly, true
}

// HasHourly returns a boolean if a field has been set.
func (o *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) HasHourly() bool {
	if o != nil && !IsNil(o.Hourly) {
		return true
	}

	return false
}

// SetHourly gets a reference to the given float32 and assigns it to the Hourly field.
func (o *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) SetHourly(v float32) {
	o.Hourly = &v
}

// GetMonthly returns the Monthly field value if set, zero value otherwise.
func (o *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) GetMonthly() float32 {
	if o == nil || IsNil(o.Monthly) {
		var ret float32
		return ret
	}
	return *o.Monthly
}

// GetMonthlyOk returns a tuple with the Monthly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) GetMonthlyOk() (*float32, bool) {
	if o == nil || IsNil(o.Monthly) {
		return nil, false
	}
	return o.Monthly, true
}

// HasMonthly returns a boolean if a field has been set.
func (o *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) HasMonthly() bool {
	if o != nil && !IsNil(o.Monthly) {
		return true
	}

	return false
}

// SetMonthly gets a reference to the given float32 and assigns it to the Monthly field.
func (o *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) SetMonthly(v float32) {
	o.Monthly = &v
}

func (o GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hourly) {
		toSerialize["hourly"] = o.Hourly
	}
	if !IsNil(o.Monthly) {
		toSerialize["monthly"] = o.Monthly
	}
	return toSerialize, nil
}

type NullableGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice struct {
	value *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice
	isSet bool
}

func (v NullableGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) Get() *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice {
	return v.value
}

func (v *NullableGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) Set(val *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice(val *GetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) *NullableGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice {
	return &NullableGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice{value: val, isSet: true}
}

func (v NullableGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLinodeTypes200ResponseDataInnerAddonsBackupsPrice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


