/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetObjectStorageSsl200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetObjectStorageSsl200Response{}

// GetObjectStorageSsl200Response If this Object Storage bucket has a corresponding TLS/SSL Certificate.
type GetObjectStorageSsl200Response struct {
	// A boolean indicating if this Bucket has a corresponding TLS/SSL certificate that was uploaded by an Account user.
	Ssl *bool `json:"ssl,omitempty"`
}

// NewGetObjectStorageSsl200Response instantiates a new GetObjectStorageSsl200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetObjectStorageSsl200Response() *GetObjectStorageSsl200Response {
	this := GetObjectStorageSsl200Response{}
	return &this
}

// NewGetObjectStorageSsl200ResponseWithDefaults instantiates a new GetObjectStorageSsl200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetObjectStorageSsl200ResponseWithDefaults() *GetObjectStorageSsl200Response {
	this := GetObjectStorageSsl200Response{}
	return &this
}

// GetSsl returns the Ssl field value if set, zero value otherwise.
func (o *GetObjectStorageSsl200Response) GetSsl() bool {
	if o == nil || IsNil(o.Ssl) {
		var ret bool
		return ret
	}
	return *o.Ssl
}

// GetSslOk returns a tuple with the Ssl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetObjectStorageSsl200Response) GetSslOk() (*bool, bool) {
	if o == nil || IsNil(o.Ssl) {
		return nil, false
	}
	return o.Ssl, true
}

// HasSsl returns a boolean if a field has been set.
func (o *GetObjectStorageSsl200Response) HasSsl() bool {
	if o != nil && !IsNil(o.Ssl) {
		return true
	}

	return false
}

// SetSsl gets a reference to the given bool and assigns it to the Ssl field.
func (o *GetObjectStorageSsl200Response) SetSsl(v bool) {
	o.Ssl = &v
}

func (o GetObjectStorageSsl200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetObjectStorageSsl200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ssl) {
		toSerialize["ssl"] = o.Ssl
	}
	return toSerialize, nil
}

type NullableGetObjectStorageSsl200Response struct {
	value *GetObjectStorageSsl200Response
	isSet bool
}

func (v NullableGetObjectStorageSsl200Response) Get() *GetObjectStorageSsl200Response {
	return v.value
}

func (v *NullableGetObjectStorageSsl200Response) Set(val *GetObjectStorageSsl200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetObjectStorageSsl200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetObjectStorageSsl200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetObjectStorageSsl200Response(val *GetObjectStorageSsl200Response) *NullableGetObjectStorageSsl200Response {
	return &NullableGetObjectStorageSsl200Response{value: val, isSet: true}
}

func (v NullableGetObjectStorageSsl200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetObjectStorageSsl200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


