/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetDatabasesInstances200ResponseAllOfDataInnerUpdates type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDatabasesInstances200ResponseAllOfDataInnerUpdates{}

// GetDatabasesInstances200ResponseAllOfDataInnerUpdates Configuration settings for automated patch update maintenance for the Managed Database.
type GetDatabasesInstances200ResponseAllOfDataInnerUpdates struct {
	// The day to perform maintenance. 1=Monday, 2=Tuesday, etc.
	DayOfWeek *int32 `json:"day_of_week,omitempty"`
	// The maximum maintenance window time in hours.
	Duration *int32 `json:"duration,omitempty"`
	// Whether maintenance occurs on a weekly or monthly basis.
	Frequency *string `json:"frequency,omitempty"`
	// The hour to begin maintenance based in UTC time.
	HourOfDay *int32 `json:"hour_of_day,omitempty"`
	// The week of the month to perform `monthly` frequency updates. Defaults to `null`.  - Required for `monthly` frequency updates.  - Must be `null` for `weekly` frequency updates.
	WeekOfMonth NullableInt32 `json:"week_of_month,omitempty"`
}

// NewGetDatabasesInstances200ResponseAllOfDataInnerUpdates instantiates a new GetDatabasesInstances200ResponseAllOfDataInnerUpdates object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDatabasesInstances200ResponseAllOfDataInnerUpdates() *GetDatabasesInstances200ResponseAllOfDataInnerUpdates {
	this := GetDatabasesInstances200ResponseAllOfDataInnerUpdates{}
	var frequency string = "weekly"
	this.Frequency = &frequency
	return &this
}

// NewGetDatabasesInstances200ResponseAllOfDataInnerUpdatesWithDefaults instantiates a new GetDatabasesInstances200ResponseAllOfDataInnerUpdates object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDatabasesInstances200ResponseAllOfDataInnerUpdatesWithDefaults() *GetDatabasesInstances200ResponseAllOfDataInnerUpdates {
	this := GetDatabasesInstances200ResponseAllOfDataInnerUpdates{}
	var frequency string = "weekly"
	this.Frequency = &frequency
	return &this
}

// GetDayOfWeek returns the DayOfWeek field value if set, zero value otherwise.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) GetDayOfWeek() int32 {
	if o == nil || IsNil(o.DayOfWeek) {
		var ret int32
		return ret
	}
	return *o.DayOfWeek
}

// GetDayOfWeekOk returns a tuple with the DayOfWeek field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) GetDayOfWeekOk() (*int32, bool) {
	if o == nil || IsNil(o.DayOfWeek) {
		return nil, false
	}
	return o.DayOfWeek, true
}

// HasDayOfWeek returns a boolean if a field has been set.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) HasDayOfWeek() bool {
	if o != nil && !IsNil(o.DayOfWeek) {
		return true
	}

	return false
}

// SetDayOfWeek gets a reference to the given int32 and assigns it to the DayOfWeek field.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) SetDayOfWeek(v int32) {
	o.DayOfWeek = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) GetDuration() int32 {
	if o == nil || IsNil(o.Duration) {
		var ret int32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) GetDurationOk() (*int32, bool) {
	if o == nil || IsNil(o.Duration) {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) HasDuration() bool {
	if o != nil && !IsNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int32 and assigns it to the Duration field.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) SetDuration(v int32) {
	o.Duration = &v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) GetFrequency() string {
	if o == nil || IsNil(o.Frequency) {
		var ret string
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) GetFrequencyOk() (*string, bool) {
	if o == nil || IsNil(o.Frequency) {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) HasFrequency() bool {
	if o != nil && !IsNil(o.Frequency) {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given string and assigns it to the Frequency field.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) SetFrequency(v string) {
	o.Frequency = &v
}

// GetHourOfDay returns the HourOfDay field value if set, zero value otherwise.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) GetHourOfDay() int32 {
	if o == nil || IsNil(o.HourOfDay) {
		var ret int32
		return ret
	}
	return *o.HourOfDay
}

// GetHourOfDayOk returns a tuple with the HourOfDay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) GetHourOfDayOk() (*int32, bool) {
	if o == nil || IsNil(o.HourOfDay) {
		return nil, false
	}
	return o.HourOfDay, true
}

// HasHourOfDay returns a boolean if a field has been set.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) HasHourOfDay() bool {
	if o != nil && !IsNil(o.HourOfDay) {
		return true
	}

	return false
}

// SetHourOfDay gets a reference to the given int32 and assigns it to the HourOfDay field.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) SetHourOfDay(v int32) {
	o.HourOfDay = &v
}

// GetWeekOfMonth returns the WeekOfMonth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) GetWeekOfMonth() int32 {
	if o == nil || IsNil(o.WeekOfMonth.Get()) {
		var ret int32
		return ret
	}
	return *o.WeekOfMonth.Get()
}

// GetWeekOfMonthOk returns a tuple with the WeekOfMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) GetWeekOfMonthOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WeekOfMonth.Get(), o.WeekOfMonth.IsSet()
}

// HasWeekOfMonth returns a boolean if a field has been set.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) HasWeekOfMonth() bool {
	if o != nil && o.WeekOfMonth.IsSet() {
		return true
	}

	return false
}

// SetWeekOfMonth gets a reference to the given NullableInt32 and assigns it to the WeekOfMonth field.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) SetWeekOfMonth(v int32) {
	o.WeekOfMonth.Set(&v)
}
// SetWeekOfMonthNil sets the value for WeekOfMonth to be an explicit nil
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) SetWeekOfMonthNil() {
	o.WeekOfMonth.Set(nil)
}

// UnsetWeekOfMonth ensures that no value is present for WeekOfMonth, not even an explicit nil
func (o *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) UnsetWeekOfMonth() {
	o.WeekOfMonth.Unset()
}

func (o GetDatabasesInstances200ResponseAllOfDataInnerUpdates) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDatabasesInstances200ResponseAllOfDataInnerUpdates) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DayOfWeek) {
		toSerialize["day_of_week"] = o.DayOfWeek
	}
	if !IsNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !IsNil(o.Frequency) {
		toSerialize["frequency"] = o.Frequency
	}
	if !IsNil(o.HourOfDay) {
		toSerialize["hour_of_day"] = o.HourOfDay
	}
	if o.WeekOfMonth.IsSet() {
		toSerialize["week_of_month"] = o.WeekOfMonth.Get()
	}
	return toSerialize, nil
}

type NullableGetDatabasesInstances200ResponseAllOfDataInnerUpdates struct {
	value *GetDatabasesInstances200ResponseAllOfDataInnerUpdates
	isSet bool
}

func (v NullableGetDatabasesInstances200ResponseAllOfDataInnerUpdates) Get() *GetDatabasesInstances200ResponseAllOfDataInnerUpdates {
	return v.value
}

func (v *NullableGetDatabasesInstances200ResponseAllOfDataInnerUpdates) Set(val *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDatabasesInstances200ResponseAllOfDataInnerUpdates) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDatabasesInstances200ResponseAllOfDataInnerUpdates) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDatabasesInstances200ResponseAllOfDataInnerUpdates(val *GetDatabasesInstances200ResponseAllOfDataInnerUpdates) *NullableGetDatabasesInstances200ResponseAllOfDataInnerUpdates {
	return &NullableGetDatabasesInstances200ResponseAllOfDataInnerUpdates{value: val, isSet: true}
}

func (v NullableGetDatabasesInstances200ResponseAllOfDataInnerUpdates) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDatabasesInstances200ResponseAllOfDataInnerUpdates) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


