/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetChildAccounts200ResponseDataInnerCreditCard type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetChildAccounts200ResponseDataInnerCreditCard{}

// GetChildAccounts200ResponseDataInnerCreditCard Information for the credit card you've assigned to this child account.
type GetChildAccounts200ResponseDataInnerCreditCard struct {
	// The expiration month and year of the credit card.
	Expiry *string `json:"expiry,omitempty"`
	// The last four digits of the credit card.
	LastFour *string `json:"last_four,omitempty"`
}

// NewGetChildAccounts200ResponseDataInnerCreditCard instantiates a new GetChildAccounts200ResponseDataInnerCreditCard object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetChildAccounts200ResponseDataInnerCreditCard() *GetChildAccounts200ResponseDataInnerCreditCard {
	this := GetChildAccounts200ResponseDataInnerCreditCard{}
	return &this
}

// NewGetChildAccounts200ResponseDataInnerCreditCardWithDefaults instantiates a new GetChildAccounts200ResponseDataInnerCreditCard object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetChildAccounts200ResponseDataInnerCreditCardWithDefaults() *GetChildAccounts200ResponseDataInnerCreditCard {
	this := GetChildAccounts200ResponseDataInnerCreditCard{}
	return &this
}

// GetExpiry returns the Expiry field value if set, zero value otherwise.
func (o *GetChildAccounts200ResponseDataInnerCreditCard) GetExpiry() string {
	if o == nil || IsNil(o.Expiry) {
		var ret string
		return ret
	}
	return *o.Expiry
}

// GetExpiryOk returns a tuple with the Expiry field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildAccounts200ResponseDataInnerCreditCard) GetExpiryOk() (*string, bool) {
	if o == nil || IsNil(o.Expiry) {
		return nil, false
	}
	return o.Expiry, true
}

// HasExpiry returns a boolean if a field has been set.
func (o *GetChildAccounts200ResponseDataInnerCreditCard) HasExpiry() bool {
	if o != nil && !IsNil(o.Expiry) {
		return true
	}

	return false
}

// SetExpiry gets a reference to the given string and assigns it to the Expiry field.
func (o *GetChildAccounts200ResponseDataInnerCreditCard) SetExpiry(v string) {
	o.Expiry = &v
}

// GetLastFour returns the LastFour field value if set, zero value otherwise.
func (o *GetChildAccounts200ResponseDataInnerCreditCard) GetLastFour() string {
	if o == nil || IsNil(o.LastFour) {
		var ret string
		return ret
	}
	return *o.LastFour
}

// GetLastFourOk returns a tuple with the LastFour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChildAccounts200ResponseDataInnerCreditCard) GetLastFourOk() (*string, bool) {
	if o == nil || IsNil(o.LastFour) {
		return nil, false
	}
	return o.LastFour, true
}

// HasLastFour returns a boolean if a field has been set.
func (o *GetChildAccounts200ResponseDataInnerCreditCard) HasLastFour() bool {
	if o != nil && !IsNil(o.LastFour) {
		return true
	}

	return false
}

// SetLastFour gets a reference to the given string and assigns it to the LastFour field.
func (o *GetChildAccounts200ResponseDataInnerCreditCard) SetLastFour(v string) {
	o.LastFour = &v
}

func (o GetChildAccounts200ResponseDataInnerCreditCard) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetChildAccounts200ResponseDataInnerCreditCard) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Expiry) {
		toSerialize["expiry"] = o.Expiry
	}
	if !IsNil(o.LastFour) {
		toSerialize["last_four"] = o.LastFour
	}
	return toSerialize, nil
}

type NullableGetChildAccounts200ResponseDataInnerCreditCard struct {
	value *GetChildAccounts200ResponseDataInnerCreditCard
	isSet bool
}

func (v NullableGetChildAccounts200ResponseDataInnerCreditCard) Get() *GetChildAccounts200ResponseDataInnerCreditCard {
	return v.value
}

func (v *NullableGetChildAccounts200ResponseDataInnerCreditCard) Set(val *GetChildAccounts200ResponseDataInnerCreditCard) {
	v.value = val
	v.isSet = true
}

func (v NullableGetChildAccounts200ResponseDataInnerCreditCard) IsSet() bool {
	return v.isSet
}

func (v *NullableGetChildAccounts200ResponseDataInnerCreditCard) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetChildAccounts200ResponseDataInnerCreditCard(val *GetChildAccounts200ResponseDataInnerCreditCard) *NullableGetChildAccounts200ResponseDataInnerCreditCard {
	return &NullableGetChildAccounts200ResponseDataInnerCreditCard{value: val, isSet: true}
}

func (v NullableGetChildAccounts200ResponseDataInnerCreditCard) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetChildAccounts200ResponseDataInnerCreditCard) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


