/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetLinodeStats200ResponseNetv4 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLinodeStats200ResponseNetv4{}

// GetLinodeStats200ResponseNetv4 IPv4 statistics.
type GetLinodeStats200ResponseNetv4 struct {
	// Input stats for IPv4, measured in bits/s (bits/second).
	In [][]float32 `json:"in,omitempty"`
	// Output stats for IPv4, measured in bits/s (bits/second).
	Out [][]float32 `json:"out,omitempty"`
	// Private IPv4 input statistics, measured in bits/s (bits/second).
	PrivateIn [][]float32 `json:"private_in,omitempty"`
	// Private IPv4 output statistics, measured in bits/s (bits/second).
	PrivateOut [][]float32 `json:"private_out,omitempty"`
}

// NewGetLinodeStats200ResponseNetv4 instantiates a new GetLinodeStats200ResponseNetv4 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLinodeStats200ResponseNetv4() *GetLinodeStats200ResponseNetv4 {
	this := GetLinodeStats200ResponseNetv4{}
	return &this
}

// NewGetLinodeStats200ResponseNetv4WithDefaults instantiates a new GetLinodeStats200ResponseNetv4 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLinodeStats200ResponseNetv4WithDefaults() *GetLinodeStats200ResponseNetv4 {
	this := GetLinodeStats200ResponseNetv4{}
	return &this
}

// GetIn returns the In field value if set, zero value otherwise.
func (o *GetLinodeStats200ResponseNetv4) GetIn() [][]float32 {
	if o == nil || IsNil(o.In) {
		var ret [][]float32
		return ret
	}
	return o.In
}

// GetInOk returns a tuple with the In field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeStats200ResponseNetv4) GetInOk() ([][]float32, bool) {
	if o == nil || IsNil(o.In) {
		return nil, false
	}
	return o.In, true
}

// HasIn returns a boolean if a field has been set.
func (o *GetLinodeStats200ResponseNetv4) HasIn() bool {
	if o != nil && !IsNil(o.In) {
		return true
	}

	return false
}

// SetIn gets a reference to the given [][]float32 and assigns it to the In field.
func (o *GetLinodeStats200ResponseNetv4) SetIn(v [][]float32) {
	o.In = v
}

// GetOut returns the Out field value if set, zero value otherwise.
func (o *GetLinodeStats200ResponseNetv4) GetOut() [][]float32 {
	if o == nil || IsNil(o.Out) {
		var ret [][]float32
		return ret
	}
	return o.Out
}

// GetOutOk returns a tuple with the Out field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeStats200ResponseNetv4) GetOutOk() ([][]float32, bool) {
	if o == nil || IsNil(o.Out) {
		return nil, false
	}
	return o.Out, true
}

// HasOut returns a boolean if a field has been set.
func (o *GetLinodeStats200ResponseNetv4) HasOut() bool {
	if o != nil && !IsNil(o.Out) {
		return true
	}

	return false
}

// SetOut gets a reference to the given [][]float32 and assigns it to the Out field.
func (o *GetLinodeStats200ResponseNetv4) SetOut(v [][]float32) {
	o.Out = v
}

// GetPrivateIn returns the PrivateIn field value if set, zero value otherwise.
func (o *GetLinodeStats200ResponseNetv4) GetPrivateIn() [][]float32 {
	if o == nil || IsNil(o.PrivateIn) {
		var ret [][]float32
		return ret
	}
	return o.PrivateIn
}

// GetPrivateInOk returns a tuple with the PrivateIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeStats200ResponseNetv4) GetPrivateInOk() ([][]float32, bool) {
	if o == nil || IsNil(o.PrivateIn) {
		return nil, false
	}
	return o.PrivateIn, true
}

// HasPrivateIn returns a boolean if a field has been set.
func (o *GetLinodeStats200ResponseNetv4) HasPrivateIn() bool {
	if o != nil && !IsNil(o.PrivateIn) {
		return true
	}

	return false
}

// SetPrivateIn gets a reference to the given [][]float32 and assigns it to the PrivateIn field.
func (o *GetLinodeStats200ResponseNetv4) SetPrivateIn(v [][]float32) {
	o.PrivateIn = v
}

// GetPrivateOut returns the PrivateOut field value if set, zero value otherwise.
func (o *GetLinodeStats200ResponseNetv4) GetPrivateOut() [][]float32 {
	if o == nil || IsNil(o.PrivateOut) {
		var ret [][]float32
		return ret
	}
	return o.PrivateOut
}

// GetPrivateOutOk returns a tuple with the PrivateOut field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeStats200ResponseNetv4) GetPrivateOutOk() ([][]float32, bool) {
	if o == nil || IsNil(o.PrivateOut) {
		return nil, false
	}
	return o.PrivateOut, true
}

// HasPrivateOut returns a boolean if a field has been set.
func (o *GetLinodeStats200ResponseNetv4) HasPrivateOut() bool {
	if o != nil && !IsNil(o.PrivateOut) {
		return true
	}

	return false
}

// SetPrivateOut gets a reference to the given [][]float32 and assigns it to the PrivateOut field.
func (o *GetLinodeStats200ResponseNetv4) SetPrivateOut(v [][]float32) {
	o.PrivateOut = v
}

func (o GetLinodeStats200ResponseNetv4) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLinodeStats200ResponseNetv4) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.In) {
		toSerialize["in"] = o.In
	}
	if !IsNil(o.Out) {
		toSerialize["out"] = o.Out
	}
	if !IsNil(o.PrivateIn) {
		toSerialize["private_in"] = o.PrivateIn
	}
	if !IsNil(o.PrivateOut) {
		toSerialize["private_out"] = o.PrivateOut
	}
	return toSerialize, nil
}

type NullableGetLinodeStats200ResponseNetv4 struct {
	value *GetLinodeStats200ResponseNetv4
	isSet bool
}

func (v NullableGetLinodeStats200ResponseNetv4) Get() *GetLinodeStats200ResponseNetv4 {
	return v.value
}

func (v *NullableGetLinodeStats200ResponseNetv4) Set(val *GetLinodeStats200ResponseNetv4) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLinodeStats200ResponseNetv4) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLinodeStats200ResponseNetv4) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLinodeStats200ResponseNetv4(val *GetLinodeStats200ResponseNetv4) *NullableGetLinodeStats200ResponseNetv4 {
	return &NullableGetLinodeStats200ResponseNetv4{value: val, isSet: true}
}

func (v NullableGetLinodeStats200ResponseNetv4) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLinodeStats200ResponseNetv4) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


