/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostLkeClusterRequestNodePoolsInnerDisksInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostLkeClusterRequestNodePoolsInnerDisksInner{}

// PostLkeClusterRequestNodePoolsInnerDisksInner The values to assign to each partition in this Node Pool's custom disk layout.
type PostLkeClusterRequestNodePoolsInnerDisksInner struct {
	// The size of this custom disk partition in MB. The size of this disk partition can't exceed the capacity of the node's plan type.
	Size *int32 `json:"size,omitempty"`
	// This custom disk partition's filesystem type.
	Type *string `json:"type,omitempty"`
}

// NewPostLkeClusterRequestNodePoolsInnerDisksInner instantiates a new PostLkeClusterRequestNodePoolsInnerDisksInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostLkeClusterRequestNodePoolsInnerDisksInner() *PostLkeClusterRequestNodePoolsInnerDisksInner {
	this := PostLkeClusterRequestNodePoolsInnerDisksInner{}
	return &this
}

// NewPostLkeClusterRequestNodePoolsInnerDisksInnerWithDefaults instantiates a new PostLkeClusterRequestNodePoolsInnerDisksInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostLkeClusterRequestNodePoolsInnerDisksInnerWithDefaults() *PostLkeClusterRequestNodePoolsInnerDisksInner {
	this := PostLkeClusterRequestNodePoolsInnerDisksInner{}
	return &this
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *PostLkeClusterRequestNodePoolsInnerDisksInner) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostLkeClusterRequestNodePoolsInnerDisksInner) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *PostLkeClusterRequestNodePoolsInnerDisksInner) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *PostLkeClusterRequestNodePoolsInnerDisksInner) SetSize(v int32) {
	o.Size = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *PostLkeClusterRequestNodePoolsInnerDisksInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostLkeClusterRequestNodePoolsInnerDisksInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *PostLkeClusterRequestNodePoolsInnerDisksInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *PostLkeClusterRequestNodePoolsInnerDisksInner) SetType(v string) {
	o.Type = &v
}

func (o PostLkeClusterRequestNodePoolsInnerDisksInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostLkeClusterRequestNodePoolsInnerDisksInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullablePostLkeClusterRequestNodePoolsInnerDisksInner struct {
	value *PostLkeClusterRequestNodePoolsInnerDisksInner
	isSet bool
}

func (v NullablePostLkeClusterRequestNodePoolsInnerDisksInner) Get() *PostLkeClusterRequestNodePoolsInnerDisksInner {
	return v.value
}

func (v *NullablePostLkeClusterRequestNodePoolsInnerDisksInner) Set(val *PostLkeClusterRequestNodePoolsInnerDisksInner) {
	v.value = val
	v.isSet = true
}

func (v NullablePostLkeClusterRequestNodePoolsInnerDisksInner) IsSet() bool {
	return v.isSet
}

func (v *NullablePostLkeClusterRequestNodePoolsInnerDisksInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostLkeClusterRequestNodePoolsInnerDisksInner(val *PostLkeClusterRequestNodePoolsInnerDisksInner) *NullablePostLkeClusterRequestNodePoolsInnerDisksInner {
	return &NullablePostLkeClusterRequestNodePoolsInnerDisksInner{value: val, isSet: true}
}

func (v NullablePostLkeClusterRequestNodePoolsInnerDisksInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostLkeClusterRequestNodePoolsInnerDisksInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


