/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PostObjectStorageObjectUrl200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostObjectStorageObjectUrl200Response{}

// PostObjectStorageObjectUrl200Response struct for PostObjectStorageObjectUrl200Response
type PostObjectStorageObjectUrl200Response struct {
	// The signed URL to perform the request at.
	Url *string `json:"url,omitempty"`
}

// NewPostObjectStorageObjectUrl200Response instantiates a new PostObjectStorageObjectUrl200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostObjectStorageObjectUrl200Response() *PostObjectStorageObjectUrl200Response {
	this := PostObjectStorageObjectUrl200Response{}
	return &this
}

// NewPostObjectStorageObjectUrl200ResponseWithDefaults instantiates a new PostObjectStorageObjectUrl200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostObjectStorageObjectUrl200ResponseWithDefaults() *PostObjectStorageObjectUrl200Response {
	this := PostObjectStorageObjectUrl200Response{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *PostObjectStorageObjectUrl200Response) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostObjectStorageObjectUrl200Response) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *PostObjectStorageObjectUrl200Response) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *PostObjectStorageObjectUrl200Response) SetUrl(v string) {
	o.Url = &v
}

func (o PostObjectStorageObjectUrl200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostObjectStorageObjectUrl200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullablePostObjectStorageObjectUrl200Response struct {
	value *PostObjectStorageObjectUrl200Response
	isSet bool
}

func (v NullablePostObjectStorageObjectUrl200Response) Get() *PostObjectStorageObjectUrl200Response {
	return v.value
}

func (v *NullablePostObjectStorageObjectUrl200Response) Set(val *PostObjectStorageObjectUrl200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostObjectStorageObjectUrl200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostObjectStorageObjectUrl200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostObjectStorageObjectUrl200Response(val *PostObjectStorageObjectUrl200Response) *NullablePostObjectStorageObjectUrl200Response {
	return &NullablePostObjectStorageObjectUrl200Response{value: val, isSet: true}
}

func (v NullablePostObjectStorageObjectUrl200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostObjectStorageObjectUrl200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


