/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostCloneLinodeInstanceRequestPlacementGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostCloneLinodeInstanceRequestPlacementGroup{}

// PostCloneLinodeInstanceRequestPlacementGroup Include this to assign this Linode to an existing [placement group](https://www.linode.com/docs/products/compute/compute-instances/guides/placement-groups/). Consider these points when cloning:  - If the Linode you're cloning exists in a placement group, the API won't automatically add the cloned instance to the same placement group. You need to specify a placement group to add the clone to. - The target placement group needs to be in the same `region` set for this Linode. - The placement group needs to have capacity. Run the [Get a region](https://techdocs.akamai.com/linode-api/reference/get-region) operation and store the `maximum_linodes_per_pg` value to know the Linode limit per placement group. You can then run the [Get a placement group](https://techdocs.akamai.com/linode-api/reference/get-placement-group) operation to review the Linodes in that group.
type PostCloneLinodeInstanceRequestPlacementGroup struct {
	// The placement group's ID. You need to provide it for all operations that affect it.
	Id int32 `json:"id"`
}

type _PostCloneLinodeInstanceRequestPlacementGroup PostCloneLinodeInstanceRequestPlacementGroup

// NewPostCloneLinodeInstanceRequestPlacementGroup instantiates a new PostCloneLinodeInstanceRequestPlacementGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostCloneLinodeInstanceRequestPlacementGroup(id int32) *PostCloneLinodeInstanceRequestPlacementGroup {
	this := PostCloneLinodeInstanceRequestPlacementGroup{}
	this.Id = id
	return &this
}

// NewPostCloneLinodeInstanceRequestPlacementGroupWithDefaults instantiates a new PostCloneLinodeInstanceRequestPlacementGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostCloneLinodeInstanceRequestPlacementGroupWithDefaults() *PostCloneLinodeInstanceRequestPlacementGroup {
	this := PostCloneLinodeInstanceRequestPlacementGroup{}
	return &this
}

// GetId returns the Id field value
func (o *PostCloneLinodeInstanceRequestPlacementGroup) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PostCloneLinodeInstanceRequestPlacementGroup) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PostCloneLinodeInstanceRequestPlacementGroup) SetId(v int32) {
	o.Id = v
}

func (o PostCloneLinodeInstanceRequestPlacementGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostCloneLinodeInstanceRequestPlacementGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *PostCloneLinodeInstanceRequestPlacementGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostCloneLinodeInstanceRequestPlacementGroup := _PostCloneLinodeInstanceRequestPlacementGroup{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostCloneLinodeInstanceRequestPlacementGroup)

	if err != nil {
		return err
	}

	*o = PostCloneLinodeInstanceRequestPlacementGroup(varPostCloneLinodeInstanceRequestPlacementGroup)

	return err
}

type NullablePostCloneLinodeInstanceRequestPlacementGroup struct {
	value *PostCloneLinodeInstanceRequestPlacementGroup
	isSet bool
}

func (v NullablePostCloneLinodeInstanceRequestPlacementGroup) Get() *PostCloneLinodeInstanceRequestPlacementGroup {
	return v.value
}

func (v *NullablePostCloneLinodeInstanceRequestPlacementGroup) Set(val *PostCloneLinodeInstanceRequestPlacementGroup) {
	v.value = val
	v.isSet = true
}

func (v NullablePostCloneLinodeInstanceRequestPlacementGroup) IsSet() bool {
	return v.isSet
}

func (v *NullablePostCloneLinodeInstanceRequestPlacementGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostCloneLinodeInstanceRequestPlacementGroup(val *PostCloneLinodeInstanceRequestPlacementGroup) *NullablePostCloneLinodeInstanceRequestPlacementGroup {
	return &NullablePostCloneLinodeInstanceRequestPlacementGroup{value: val, isSet: true}
}

func (v NullablePostCloneLinodeInstanceRequestPlacementGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostCloneLinodeInstanceRequestPlacementGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


