/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetDomainZone200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDomainZone200Response{}

// GetDomainZone200Response struct for GetDomainZone200Response
type GetDomainZone200Response struct {
	// The lines of the zone file for the last rendered zone for this domain.
	ZoneFile []string `json:"zone_file,omitempty"`
}

// NewGetDomainZone200Response instantiates a new GetDomainZone200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDomainZone200Response() *GetDomainZone200Response {
	this := GetDomainZone200Response{}
	return &this
}

// NewGetDomainZone200ResponseWithDefaults instantiates a new GetDomainZone200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDomainZone200ResponseWithDefaults() *GetDomainZone200Response {
	this := GetDomainZone200Response{}
	return &this
}

// GetZoneFile returns the ZoneFile field value if set, zero value otherwise.
func (o *GetDomainZone200Response) GetZoneFile() []string {
	if o == nil || IsNil(o.ZoneFile) {
		var ret []string
		return ret
	}
	return o.ZoneFile
}

// GetZoneFileOk returns a tuple with the ZoneFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDomainZone200Response) GetZoneFileOk() ([]string, bool) {
	if o == nil || IsNil(o.ZoneFile) {
		return nil, false
	}
	return o.ZoneFile, true
}

// HasZoneFile returns a boolean if a field has been set.
func (o *GetDomainZone200Response) HasZoneFile() bool {
	if o != nil && !IsNil(o.ZoneFile) {
		return true
	}

	return false
}

// SetZoneFile gets a reference to the given []string and assigns it to the ZoneFile field.
func (o *GetDomainZone200Response) SetZoneFile(v []string) {
	o.ZoneFile = v
}

func (o GetDomainZone200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDomainZone200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ZoneFile) {
		toSerialize["zone_file"] = o.ZoneFile
	}
	return toSerialize, nil
}

type NullableGetDomainZone200Response struct {
	value *GetDomainZone200Response
	isSet bool
}

func (v NullableGetDomainZone200Response) Get() *GetDomainZone200Response {
	return v.value
}

func (v *NullableGetDomainZone200Response) Set(val *GetDomainZone200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDomainZone200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDomainZone200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDomainZone200Response(val *GetDomainZone200Response) *NullableGetDomainZone200Response {
	return &NullableGetDomainZone200Response{value: val, isSet: true}
}

func (v NullableGetDomainZone200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDomainZone200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


