/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AddedGetEnrolledBetaPrograms200 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddedGetEnrolledBetaPrograms200{}

// AddedGetEnrolledBetaPrograms200 struct for AddedGetEnrolledBetaPrograms200
type AddedGetEnrolledBetaPrograms200 struct {
	// The current [page](https://techdocs.akamai.com/linode-api/reference/pagination).
	Page *int32 `json:"page,omitempty"`
	// The total number of [pages](https://techdocs.akamai.com/linode-api/reference/pagination).
	Pages *int32 `json:"pages,omitempty"`
	// The total number of results.
	Results *int32 `json:"results,omitempty"`
	Data []AddedGetEnrolledBetaPrograms200AllOfData `json:"data,omitempty"`
}

// NewAddedGetEnrolledBetaPrograms200 instantiates a new AddedGetEnrolledBetaPrograms200 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddedGetEnrolledBetaPrograms200() *AddedGetEnrolledBetaPrograms200 {
	this := AddedGetEnrolledBetaPrograms200{}
	return &this
}

// NewAddedGetEnrolledBetaPrograms200WithDefaults instantiates a new AddedGetEnrolledBetaPrograms200 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddedGetEnrolledBetaPrograms200WithDefaults() *AddedGetEnrolledBetaPrograms200 {
	this := AddedGetEnrolledBetaPrograms200{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *AddedGetEnrolledBetaPrograms200) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddedGetEnrolledBetaPrograms200) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *AddedGetEnrolledBetaPrograms200) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *AddedGetEnrolledBetaPrograms200) SetPage(v int32) {
	o.Page = &v
}

// GetPages returns the Pages field value if set, zero value otherwise.
func (o *AddedGetEnrolledBetaPrograms200) GetPages() int32 {
	if o == nil || IsNil(o.Pages) {
		var ret int32
		return ret
	}
	return *o.Pages
}

// GetPagesOk returns a tuple with the Pages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddedGetEnrolledBetaPrograms200) GetPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.Pages) {
		return nil, false
	}
	return o.Pages, true
}

// HasPages returns a boolean if a field has been set.
func (o *AddedGetEnrolledBetaPrograms200) HasPages() bool {
	if o != nil && !IsNil(o.Pages) {
		return true
	}

	return false
}

// SetPages gets a reference to the given int32 and assigns it to the Pages field.
func (o *AddedGetEnrolledBetaPrograms200) SetPages(v int32) {
	o.Pages = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *AddedGetEnrolledBetaPrograms200) GetResults() int32 {
	if o == nil || IsNil(o.Results) {
		var ret int32
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddedGetEnrolledBetaPrograms200) GetResultsOk() (*int32, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *AddedGetEnrolledBetaPrograms200) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given int32 and assigns it to the Results field.
func (o *AddedGetEnrolledBetaPrograms200) SetResults(v int32) {
	o.Results = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AddedGetEnrolledBetaPrograms200) GetData() []AddedGetEnrolledBetaPrograms200AllOfData {
	if o == nil || IsNil(o.Data) {
		var ret []AddedGetEnrolledBetaPrograms200AllOfData
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddedGetEnrolledBetaPrograms200) GetDataOk() ([]AddedGetEnrolledBetaPrograms200AllOfData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AddedGetEnrolledBetaPrograms200) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []AddedGetEnrolledBetaPrograms200AllOfData and assigns it to the Data field.
func (o *AddedGetEnrolledBetaPrograms200) SetData(v []AddedGetEnrolledBetaPrograms200AllOfData) {
	o.Data = v
}

func (o AddedGetEnrolledBetaPrograms200) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddedGetEnrolledBetaPrograms200) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Pages) {
		toSerialize["pages"] = o.Pages
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAddedGetEnrolledBetaPrograms200 struct {
	value *AddedGetEnrolledBetaPrograms200
	isSet bool
}

func (v NullableAddedGetEnrolledBetaPrograms200) Get() *AddedGetEnrolledBetaPrograms200 {
	return v.value
}

func (v *NullableAddedGetEnrolledBetaPrograms200) Set(val *AddedGetEnrolledBetaPrograms200) {
	v.value = val
	v.isSet = true
}

func (v NullableAddedGetEnrolledBetaPrograms200) IsSet() bool {
	return v.isSet
}

func (v *NullableAddedGetEnrolledBetaPrograms200) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddedGetEnrolledBetaPrograms200(val *AddedGetEnrolledBetaPrograms200) *NullableAddedGetEnrolledBetaPrograms200 {
	return &NullableAddedGetEnrolledBetaPrograms200{value: val, isSet: true}
}

func (v NullableAddedGetEnrolledBetaPrograms200) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddedGetEnrolledBetaPrograms200) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


