/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetIpv6Pools200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetIpv6Pools200ResponseDataInner{}

// GetIpv6Pools200ResponseDataInner An object representing an IPv6 pool.
type GetIpv6Pools200ResponseDataInner struct {
	// The prefix length of the address. The total number of addresses that can be assigned from this range is calculated as 2<sup>(128 - prefix length)</sup>.
	Prefix *int32 `json:"prefix,omitempty"`
	// The IPv6 range of addresses in this pool.
	Range *string `json:"range,omitempty"`
	// The region for this pool of IPv6 addresses.
	Region *string `json:"region,omitempty"`
	// The last address in this block of IPv6 addresses.
	RouteTarget NullableString `json:"route_target,omitempty"`
}

// NewGetIpv6Pools200ResponseDataInner instantiates a new GetIpv6Pools200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetIpv6Pools200ResponseDataInner() *GetIpv6Pools200ResponseDataInner {
	this := GetIpv6Pools200ResponseDataInner{}
	return &this
}

// NewGetIpv6Pools200ResponseDataInnerWithDefaults instantiates a new GetIpv6Pools200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetIpv6Pools200ResponseDataInnerWithDefaults() *GetIpv6Pools200ResponseDataInner {
	this := GetIpv6Pools200ResponseDataInner{}
	return &this
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *GetIpv6Pools200ResponseDataInner) GetPrefix() int32 {
	if o == nil || IsNil(o.Prefix) {
		var ret int32
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIpv6Pools200ResponseDataInner) GetPrefixOk() (*int32, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *GetIpv6Pools200ResponseDataInner) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given int32 and assigns it to the Prefix field.
func (o *GetIpv6Pools200ResponseDataInner) SetPrefix(v int32) {
	o.Prefix = &v
}

// GetRange returns the Range field value if set, zero value otherwise.
func (o *GetIpv6Pools200ResponseDataInner) GetRange() string {
	if o == nil || IsNil(o.Range) {
		var ret string
		return ret
	}
	return *o.Range
}

// GetRangeOk returns a tuple with the Range field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIpv6Pools200ResponseDataInner) GetRangeOk() (*string, bool) {
	if o == nil || IsNil(o.Range) {
		return nil, false
	}
	return o.Range, true
}

// HasRange returns a boolean if a field has been set.
func (o *GetIpv6Pools200ResponseDataInner) HasRange() bool {
	if o != nil && !IsNil(o.Range) {
		return true
	}

	return false
}

// SetRange gets a reference to the given string and assigns it to the Range field.
func (o *GetIpv6Pools200ResponseDataInner) SetRange(v string) {
	o.Range = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *GetIpv6Pools200ResponseDataInner) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetIpv6Pools200ResponseDataInner) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *GetIpv6Pools200ResponseDataInner) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *GetIpv6Pools200ResponseDataInner) SetRegion(v string) {
	o.Region = &v
}

// GetRouteTarget returns the RouteTarget field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetIpv6Pools200ResponseDataInner) GetRouteTarget() string {
	if o == nil || IsNil(o.RouteTarget.Get()) {
		var ret string
		return ret
	}
	return *o.RouteTarget.Get()
}

// GetRouteTargetOk returns a tuple with the RouteTarget field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetIpv6Pools200ResponseDataInner) GetRouteTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RouteTarget.Get(), o.RouteTarget.IsSet()
}

// HasRouteTarget returns a boolean if a field has been set.
func (o *GetIpv6Pools200ResponseDataInner) HasRouteTarget() bool {
	if o != nil && o.RouteTarget.IsSet() {
		return true
	}

	return false
}

// SetRouteTarget gets a reference to the given NullableString and assigns it to the RouteTarget field.
func (o *GetIpv6Pools200ResponseDataInner) SetRouteTarget(v string) {
	o.RouteTarget.Set(&v)
}
// SetRouteTargetNil sets the value for RouteTarget to be an explicit nil
func (o *GetIpv6Pools200ResponseDataInner) SetRouteTargetNil() {
	o.RouteTarget.Set(nil)
}

// UnsetRouteTarget ensures that no value is present for RouteTarget, not even an explicit nil
func (o *GetIpv6Pools200ResponseDataInner) UnsetRouteTarget() {
	o.RouteTarget.Unset()
}

func (o GetIpv6Pools200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetIpv6Pools200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prefix) {
		toSerialize["prefix"] = o.Prefix
	}
	if !IsNil(o.Range) {
		toSerialize["range"] = o.Range
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if o.RouteTarget.IsSet() {
		toSerialize["route_target"] = o.RouteTarget.Get()
	}
	return toSerialize, nil
}

type NullableGetIpv6Pools200ResponseDataInner struct {
	value *GetIpv6Pools200ResponseDataInner
	isSet bool
}

func (v NullableGetIpv6Pools200ResponseDataInner) Get() *GetIpv6Pools200ResponseDataInner {
	return v.value
}

func (v *NullableGetIpv6Pools200ResponseDataInner) Set(val *GetIpv6Pools200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetIpv6Pools200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetIpv6Pools200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetIpv6Pools200ResponseDataInner(val *GetIpv6Pools200ResponseDataInner) *NullableGetIpv6Pools200ResponseDataInner {
	return &NullableGetIpv6Pools200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetIpv6Pools200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetIpv6Pools200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


