/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostManagedCredentialUsernamePasswordRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostManagedCredentialUsernamePasswordRequest{}

// PostManagedCredentialUsernamePasswordRequest struct for PostManagedCredentialUsernamePasswordRequest
type PostManagedCredentialUsernamePasswordRequest struct {
	// The password to use when accessing the Managed Service.
	Password string `json:"password"`
	// The username to use when accessing the Managed Service.
	Username *string `json:"username,omitempty"`
}

type _PostManagedCredentialUsernamePasswordRequest PostManagedCredentialUsernamePasswordRequest

// NewPostManagedCredentialUsernamePasswordRequest instantiates a new PostManagedCredentialUsernamePasswordRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostManagedCredentialUsernamePasswordRequest(password string) *PostManagedCredentialUsernamePasswordRequest {
	this := PostManagedCredentialUsernamePasswordRequest{}
	this.Password = password
	return &this
}

// NewPostManagedCredentialUsernamePasswordRequestWithDefaults instantiates a new PostManagedCredentialUsernamePasswordRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostManagedCredentialUsernamePasswordRequestWithDefaults() *PostManagedCredentialUsernamePasswordRequest {
	this := PostManagedCredentialUsernamePasswordRequest{}
	return &this
}

// GetPassword returns the Password field value
func (o *PostManagedCredentialUsernamePasswordRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *PostManagedCredentialUsernamePasswordRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *PostManagedCredentialUsernamePasswordRequest) SetPassword(v string) {
	o.Password = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *PostManagedCredentialUsernamePasswordRequest) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostManagedCredentialUsernamePasswordRequest) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *PostManagedCredentialUsernamePasswordRequest) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *PostManagedCredentialUsernamePasswordRequest) SetUsername(v string) {
	o.Username = &v
}

func (o PostManagedCredentialUsernamePasswordRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostManagedCredentialUsernamePasswordRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["password"] = o.Password
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

func (o *PostManagedCredentialUsernamePasswordRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostManagedCredentialUsernamePasswordRequest := _PostManagedCredentialUsernamePasswordRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostManagedCredentialUsernamePasswordRequest)

	if err != nil {
		return err
	}

	*o = PostManagedCredentialUsernamePasswordRequest(varPostManagedCredentialUsernamePasswordRequest)

	return err
}

type NullablePostManagedCredentialUsernamePasswordRequest struct {
	value *PostManagedCredentialUsernamePasswordRequest
	isSet bool
}

func (v NullablePostManagedCredentialUsernamePasswordRequest) Get() *PostManagedCredentialUsernamePasswordRequest {
	return v.value
}

func (v *NullablePostManagedCredentialUsernamePasswordRequest) Set(val *PostManagedCredentialUsernamePasswordRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostManagedCredentialUsernamePasswordRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostManagedCredentialUsernamePasswordRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostManagedCredentialUsernamePasswordRequest(val *PostManagedCredentialUsernamePasswordRequest) *NullablePostManagedCredentialUsernamePasswordRequest {
	return &NullablePostManagedCredentialUsernamePasswordRequest{value: val, isSet: true}
}

func (v NullablePostManagedCredentialUsernamePasswordRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostManagedCredentialUsernamePasswordRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


