/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the GetKernels200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetKernels200ResponseDataInner{}

// GetKernels200ResponseDataInner Linux kernel object.
type GetKernels200ResponseDataInner struct {
	// The architecture of this Kernel.
	Architecture *string `json:"architecture,omitempty"`
	// The date on which this Kernel was built.
	Built *time.Time `json:"built,omitempty"`
	// If this Kernel is marked as deprecated, this field has a value of true; otherwise, this field is false.
	Deprecated *bool `json:"deprecated,omitempty"`
	// The unique ID of this Kernel.
	Id *string `json:"id,omitempty"`
	// If this Kernel is suitable for KVM Linodes.
	Kvm *bool `json:"kvm,omitempty"`
	// The friendly name of this Kernel.
	Label *string `json:"label,omitempty"`
	// If this Kernel is suitable for paravirtualized operations.
	Pvops *bool `json:"pvops,omitempty"`
	// Linux Kernel version.
	Version *string `json:"version,omitempty"`
}

// NewGetKernels200ResponseDataInner instantiates a new GetKernels200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetKernels200ResponseDataInner() *GetKernels200ResponseDataInner {
	this := GetKernels200ResponseDataInner{}
	return &this
}

// NewGetKernels200ResponseDataInnerWithDefaults instantiates a new GetKernels200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetKernels200ResponseDataInnerWithDefaults() *GetKernels200ResponseDataInner {
	this := GetKernels200ResponseDataInner{}
	return &this
}

// GetArchitecture returns the Architecture field value if set, zero value otherwise.
func (o *GetKernels200ResponseDataInner) GetArchitecture() string {
	if o == nil || IsNil(o.Architecture) {
		var ret string
		return ret
	}
	return *o.Architecture
}

// GetArchitectureOk returns a tuple with the Architecture field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetKernels200ResponseDataInner) GetArchitectureOk() (*string, bool) {
	if o == nil || IsNil(o.Architecture) {
		return nil, false
	}
	return o.Architecture, true
}

// HasArchitecture returns a boolean if a field has been set.
func (o *GetKernels200ResponseDataInner) HasArchitecture() bool {
	if o != nil && !IsNil(o.Architecture) {
		return true
	}

	return false
}

// SetArchitecture gets a reference to the given string and assigns it to the Architecture field.
func (o *GetKernels200ResponseDataInner) SetArchitecture(v string) {
	o.Architecture = &v
}

// GetBuilt returns the Built field value if set, zero value otherwise.
func (o *GetKernels200ResponseDataInner) GetBuilt() time.Time {
	if o == nil || IsNil(o.Built) {
		var ret time.Time
		return ret
	}
	return *o.Built
}

// GetBuiltOk returns a tuple with the Built field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetKernels200ResponseDataInner) GetBuiltOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Built) {
		return nil, false
	}
	return o.Built, true
}

// HasBuilt returns a boolean if a field has been set.
func (o *GetKernels200ResponseDataInner) HasBuilt() bool {
	if o != nil && !IsNil(o.Built) {
		return true
	}

	return false
}

// SetBuilt gets a reference to the given time.Time and assigns it to the Built field.
func (o *GetKernels200ResponseDataInner) SetBuilt(v time.Time) {
	o.Built = &v
}

// GetDeprecated returns the Deprecated field value if set, zero value otherwise.
func (o *GetKernels200ResponseDataInner) GetDeprecated() bool {
	if o == nil || IsNil(o.Deprecated) {
		var ret bool
		return ret
	}
	return *o.Deprecated
}

// GetDeprecatedOk returns a tuple with the Deprecated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetKernels200ResponseDataInner) GetDeprecatedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deprecated) {
		return nil, false
	}
	return o.Deprecated, true
}

// HasDeprecated returns a boolean if a field has been set.
func (o *GetKernels200ResponseDataInner) HasDeprecated() bool {
	if o != nil && !IsNil(o.Deprecated) {
		return true
	}

	return false
}

// SetDeprecated gets a reference to the given bool and assigns it to the Deprecated field.
func (o *GetKernels200ResponseDataInner) SetDeprecated(v bool) {
	o.Deprecated = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetKernels200ResponseDataInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetKernels200ResponseDataInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetKernels200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetKernels200ResponseDataInner) SetId(v string) {
	o.Id = &v
}

// GetKvm returns the Kvm field value if set, zero value otherwise.
func (o *GetKernels200ResponseDataInner) GetKvm() bool {
	if o == nil || IsNil(o.Kvm) {
		var ret bool
		return ret
	}
	return *o.Kvm
}

// GetKvmOk returns a tuple with the Kvm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetKernels200ResponseDataInner) GetKvmOk() (*bool, bool) {
	if o == nil || IsNil(o.Kvm) {
		return nil, false
	}
	return o.Kvm, true
}

// HasKvm returns a boolean if a field has been set.
func (o *GetKernels200ResponseDataInner) HasKvm() bool {
	if o != nil && !IsNil(o.Kvm) {
		return true
	}

	return false
}

// SetKvm gets a reference to the given bool and assigns it to the Kvm field.
func (o *GetKernels200ResponseDataInner) SetKvm(v bool) {
	o.Kvm = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *GetKernels200ResponseDataInner) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetKernels200ResponseDataInner) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *GetKernels200ResponseDataInner) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *GetKernels200ResponseDataInner) SetLabel(v string) {
	o.Label = &v
}

// GetPvops returns the Pvops field value if set, zero value otherwise.
func (o *GetKernels200ResponseDataInner) GetPvops() bool {
	if o == nil || IsNil(o.Pvops) {
		var ret bool
		return ret
	}
	return *o.Pvops
}

// GetPvopsOk returns a tuple with the Pvops field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetKernels200ResponseDataInner) GetPvopsOk() (*bool, bool) {
	if o == nil || IsNil(o.Pvops) {
		return nil, false
	}
	return o.Pvops, true
}

// HasPvops returns a boolean if a field has been set.
func (o *GetKernels200ResponseDataInner) HasPvops() bool {
	if o != nil && !IsNil(o.Pvops) {
		return true
	}

	return false
}

// SetPvops gets a reference to the given bool and assigns it to the Pvops field.
func (o *GetKernels200ResponseDataInner) SetPvops(v bool) {
	o.Pvops = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *GetKernels200ResponseDataInner) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetKernels200ResponseDataInner) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *GetKernels200ResponseDataInner) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *GetKernels200ResponseDataInner) SetVersion(v string) {
	o.Version = &v
}

func (o GetKernels200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetKernels200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Architecture) {
		toSerialize["architecture"] = o.Architecture
	}
	if !IsNil(o.Built) {
		toSerialize["built"] = o.Built
	}
	if !IsNil(o.Deprecated) {
		toSerialize["deprecated"] = o.Deprecated
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kvm) {
		toSerialize["kvm"] = o.Kvm
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Pvops) {
		toSerialize["pvops"] = o.Pvops
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableGetKernels200ResponseDataInner struct {
	value *GetKernels200ResponseDataInner
	isSet bool
}

func (v NullableGetKernels200ResponseDataInner) Get() *GetKernels200ResponseDataInner {
	return v.value
}

func (v *NullableGetKernels200ResponseDataInner) Set(val *GetKernels200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetKernels200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetKernels200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetKernels200ResponseDataInner(val *GetKernels200ResponseDataInner) *NullableGetKernels200ResponseDataInner {
	return &NullableGetKernels200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetKernels200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetKernels200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


