/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetObjectStorageKeys200ResponseDataInnerRegionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetObjectStorageKeys200ResponseDataInnerRegionsInner{}

// GetObjectStorageKeys200ResponseDataInnerRegionsInner struct for GetObjectStorageKeys200ResponseDataInnerRegionsInner
type GetObjectStorageKeys200ResponseDataInnerRegionsInner struct {
	// Identifies each region where you can use the Object Storage key.
	Id *string `json:"id,omitempty"`
	// The S3-compatible hostname you can use to access the Object Storage buckets in this region.
	S3Endpoint *string `json:"s3_endpoint,omitempty"`
}

// NewGetObjectStorageKeys200ResponseDataInnerRegionsInner instantiates a new GetObjectStorageKeys200ResponseDataInnerRegionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetObjectStorageKeys200ResponseDataInnerRegionsInner() *GetObjectStorageKeys200ResponseDataInnerRegionsInner {
	this := GetObjectStorageKeys200ResponseDataInnerRegionsInner{}
	return &this
}

// NewGetObjectStorageKeys200ResponseDataInnerRegionsInnerWithDefaults instantiates a new GetObjectStorageKeys200ResponseDataInnerRegionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetObjectStorageKeys200ResponseDataInnerRegionsInnerWithDefaults() *GetObjectStorageKeys200ResponseDataInnerRegionsInner {
	this := GetObjectStorageKeys200ResponseDataInnerRegionsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetObjectStorageKeys200ResponseDataInnerRegionsInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetObjectStorageKeys200ResponseDataInnerRegionsInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetObjectStorageKeys200ResponseDataInnerRegionsInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *GetObjectStorageKeys200ResponseDataInnerRegionsInner) SetId(v string) {
	o.Id = &v
}

// GetS3Endpoint returns the S3Endpoint field value if set, zero value otherwise.
func (o *GetObjectStorageKeys200ResponseDataInnerRegionsInner) GetS3Endpoint() string {
	if o == nil || IsNil(o.S3Endpoint) {
		var ret string
		return ret
	}
	return *o.S3Endpoint
}

// GetS3EndpointOk returns a tuple with the S3Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetObjectStorageKeys200ResponseDataInnerRegionsInner) GetS3EndpointOk() (*string, bool) {
	if o == nil || IsNil(o.S3Endpoint) {
		return nil, false
	}
	return o.S3Endpoint, true
}

// HasS3Endpoint returns a boolean if a field has been set.
func (o *GetObjectStorageKeys200ResponseDataInnerRegionsInner) HasS3Endpoint() bool {
	if o != nil && !IsNil(o.S3Endpoint) {
		return true
	}

	return false
}

// SetS3Endpoint gets a reference to the given string and assigns it to the S3Endpoint field.
func (o *GetObjectStorageKeys200ResponseDataInnerRegionsInner) SetS3Endpoint(v string) {
	o.S3Endpoint = &v
}

func (o GetObjectStorageKeys200ResponseDataInnerRegionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetObjectStorageKeys200ResponseDataInnerRegionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.S3Endpoint) {
		toSerialize["s3_endpoint"] = o.S3Endpoint
	}
	return toSerialize, nil
}

type NullableGetObjectStorageKeys200ResponseDataInnerRegionsInner struct {
	value *GetObjectStorageKeys200ResponseDataInnerRegionsInner
	isSet bool
}

func (v NullableGetObjectStorageKeys200ResponseDataInnerRegionsInner) Get() *GetObjectStorageKeys200ResponseDataInnerRegionsInner {
	return v.value
}

func (v *NullableGetObjectStorageKeys200ResponseDataInnerRegionsInner) Set(val *GetObjectStorageKeys200ResponseDataInnerRegionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetObjectStorageKeys200ResponseDataInnerRegionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetObjectStorageKeys200ResponseDataInnerRegionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetObjectStorageKeys200ResponseDataInnerRegionsInner(val *GetObjectStorageKeys200ResponseDataInnerRegionsInner) *NullableGetObjectStorageKeys200ResponseDataInnerRegionsInner {
	return &NullableGetObjectStorageKeys200ResponseDataInnerRegionsInner{value: val, isSet: true}
}

func (v NullableGetObjectStorageKeys200ResponseDataInnerRegionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetObjectStorageKeys200ResponseDataInnerRegionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


