/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetDatabasesInstances200ResponseAllOfDataInnerHosts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDatabasesInstances200ResponseAllOfDataInnerHosts{}

// GetDatabasesInstances200ResponseAllOfDataInnerHosts The primary and secondary hosts for the Managed Database. These are assigned after provisioning is complete.
type GetDatabasesInstances200ResponseAllOfDataInnerHosts struct {
	// The primary host for the Managed Database.
	Primary NullableString `json:"primary,omitempty"`
	// The secondary/private network host for the Managed Database.  A private network host and a private IP can only be used to access a Database Cluster from Linodes in the same data center and will not incur transfer costs.  __Note__. The secondary hostname is publicly viewable and accessible.
	Secondary NullableString `json:"secondary,omitempty"`
}

// NewGetDatabasesInstances200ResponseAllOfDataInnerHosts instantiates a new GetDatabasesInstances200ResponseAllOfDataInnerHosts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDatabasesInstances200ResponseAllOfDataInnerHosts() *GetDatabasesInstances200ResponseAllOfDataInnerHosts {
	this := GetDatabasesInstances200ResponseAllOfDataInnerHosts{}
	return &this
}

// NewGetDatabasesInstances200ResponseAllOfDataInnerHostsWithDefaults instantiates a new GetDatabasesInstances200ResponseAllOfDataInnerHosts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDatabasesInstances200ResponseAllOfDataInnerHostsWithDefaults() *GetDatabasesInstances200ResponseAllOfDataInnerHosts {
	this := GetDatabasesInstances200ResponseAllOfDataInnerHosts{}
	return &this
}

// GetPrimary returns the Primary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) GetPrimary() string {
	if o == nil || IsNil(o.Primary.Get()) {
		var ret string
		return ret
	}
	return *o.Primary.Get()
}

// GetPrimaryOk returns a tuple with the Primary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) GetPrimaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Primary.Get(), o.Primary.IsSet()
}

// HasPrimary returns a boolean if a field has been set.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) HasPrimary() bool {
	if o != nil && o.Primary.IsSet() {
		return true
	}

	return false
}

// SetPrimary gets a reference to the given NullableString and assigns it to the Primary field.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) SetPrimary(v string) {
	o.Primary.Set(&v)
}
// SetPrimaryNil sets the value for Primary to be an explicit nil
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) SetPrimaryNil() {
	o.Primary.Set(nil)
}

// UnsetPrimary ensures that no value is present for Primary, not even an explicit nil
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) UnsetPrimary() {
	o.Primary.Unset()
}

// GetSecondary returns the Secondary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) GetSecondary() string {
	if o == nil || IsNil(o.Secondary.Get()) {
		var ret string
		return ret
	}
	return *o.Secondary.Get()
}

// GetSecondaryOk returns a tuple with the Secondary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) GetSecondaryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Secondary.Get(), o.Secondary.IsSet()
}

// HasSecondary returns a boolean if a field has been set.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) HasSecondary() bool {
	if o != nil && o.Secondary.IsSet() {
		return true
	}

	return false
}

// SetSecondary gets a reference to the given NullableString and assigns it to the Secondary field.
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) SetSecondary(v string) {
	o.Secondary.Set(&v)
}
// SetSecondaryNil sets the value for Secondary to be an explicit nil
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) SetSecondaryNil() {
	o.Secondary.Set(nil)
}

// UnsetSecondary ensures that no value is present for Secondary, not even an explicit nil
func (o *GetDatabasesInstances200ResponseAllOfDataInnerHosts) UnsetSecondary() {
	o.Secondary.Unset()
}

func (o GetDatabasesInstances200ResponseAllOfDataInnerHosts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDatabasesInstances200ResponseAllOfDataInnerHosts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Primary.IsSet() {
		toSerialize["primary"] = o.Primary.Get()
	}
	if o.Secondary.IsSet() {
		toSerialize["secondary"] = o.Secondary.Get()
	}
	return toSerialize, nil
}

type NullableGetDatabasesInstances200ResponseAllOfDataInnerHosts struct {
	value *GetDatabasesInstances200ResponseAllOfDataInnerHosts
	isSet bool
}

func (v NullableGetDatabasesInstances200ResponseAllOfDataInnerHosts) Get() *GetDatabasesInstances200ResponseAllOfDataInnerHosts {
	return v.value
}

func (v *NullableGetDatabasesInstances200ResponseAllOfDataInnerHosts) Set(val *GetDatabasesInstances200ResponseAllOfDataInnerHosts) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDatabasesInstances200ResponseAllOfDataInnerHosts) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDatabasesInstances200ResponseAllOfDataInnerHosts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDatabasesInstances200ResponseAllOfDataInnerHosts(val *GetDatabasesInstances200ResponseAllOfDataInnerHosts) *NullableGetDatabasesInstances200ResponseAllOfDataInnerHosts {
	return &NullableGetDatabasesInstances200ResponseAllOfDataInnerHosts{value: val, isSet: true}
}

func (v NullableGetDatabasesInstances200ResponseAllOfDataInnerHosts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDatabasesInstances200ResponseAllOfDataInnerHosts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


