/*
Linode API

[Read the API documentation](https://techdocs.akamai.com/linode-api/reference/api).

API version: 4.189.2
Contact: support@linode.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetLinodeFirewalls200ResponseDataInnerRules type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLinodeFirewalls200ResponseDataInnerRules{}

// GetLinodeFirewalls200ResponseDataInnerRules The inbound and outbound access rules to apply to the Firewall.  A Firewall may have up to 25 rules across its inbound and outbound rulesets.  Multiple rules are applied in order. If two rules conflict, the first rule takes precedence. For example, if the first rule accepts inbound traffic from an address, and the second rule drops inbound traffic the same address, the first rule applies and inbound traffic from that address is accepted.
type GetLinodeFirewalls200ResponseDataInnerRules struct {
	// The fingerprint is a 32-bit hash. It represents the firewall rules as an 8 character hex string. You can use `fingerprint` to compare rule versions.
	Fingerprint *string `json:"fingerprint,omitempty"`
	// The inbound rules for the firewall, as a JSON array.
	Inbound []GetLinodeFirewalls200ResponseDataInnerRulesInboundInner `json:"inbound,omitempty"`
	// The default behavior for inbound traffic. This setting can be overridden by [updating](https://techdocs.akamai.com/linode-api/reference/put-firewall-rules) the `inbound.action` property of the Firewall Rule.
	InboundPolicy *string `json:"inbound_policy,omitempty"`
	// The outbound rules for the firewall, as a JSON array.
	Outbound []GetLinodeFirewalls200ResponseDataInnerRulesInboundInner `json:"outbound,omitempty"`
	// The default behavior for outbound traffic. This setting can be overridden by [updating](https://techdocs.akamai.com/linode-api/reference/put-firewall-rules) the `outbound.action` property of the Firewall Rule.
	OutboundPolicy *string `json:"outbound_policy,omitempty"`
	// The firewall's rule version. The first version is `1`. The version number is incremented when the firewall's rules change.
	Version *int32 `json:"version,omitempty"`
}

// NewGetLinodeFirewalls200ResponseDataInnerRules instantiates a new GetLinodeFirewalls200ResponseDataInnerRules object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLinodeFirewalls200ResponseDataInnerRules() *GetLinodeFirewalls200ResponseDataInnerRules {
	this := GetLinodeFirewalls200ResponseDataInnerRules{}
	return &this
}

// NewGetLinodeFirewalls200ResponseDataInnerRulesWithDefaults instantiates a new GetLinodeFirewalls200ResponseDataInnerRules object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLinodeFirewalls200ResponseDataInnerRulesWithDefaults() *GetLinodeFirewalls200ResponseDataInnerRules {
	this := GetLinodeFirewalls200ResponseDataInnerRules{}
	return &this
}

// GetFingerprint returns the Fingerprint field value if set, zero value otherwise.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetFingerprint() string {
	if o == nil || IsNil(o.Fingerprint) {
		var ret string
		return ret
	}
	return *o.Fingerprint
}

// GetFingerprintOk returns a tuple with the Fingerprint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetFingerprintOk() (*string, bool) {
	if o == nil || IsNil(o.Fingerprint) {
		return nil, false
	}
	return o.Fingerprint, true
}

// HasFingerprint returns a boolean if a field has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) HasFingerprint() bool {
	if o != nil && !IsNil(o.Fingerprint) {
		return true
	}

	return false
}

// SetFingerprint gets a reference to the given string and assigns it to the Fingerprint field.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) SetFingerprint(v string) {
	o.Fingerprint = &v
}

// GetInbound returns the Inbound field value if set, zero value otherwise.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetInbound() []GetLinodeFirewalls200ResponseDataInnerRulesInboundInner {
	if o == nil || IsNil(o.Inbound) {
		var ret []GetLinodeFirewalls200ResponseDataInnerRulesInboundInner
		return ret
	}
	return o.Inbound
}

// GetInboundOk returns a tuple with the Inbound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetInboundOk() ([]GetLinodeFirewalls200ResponseDataInnerRulesInboundInner, bool) {
	if o == nil || IsNil(o.Inbound) {
		return nil, false
	}
	return o.Inbound, true
}

// HasInbound returns a boolean if a field has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) HasInbound() bool {
	if o != nil && !IsNil(o.Inbound) {
		return true
	}

	return false
}

// SetInbound gets a reference to the given []GetLinodeFirewalls200ResponseDataInnerRulesInboundInner and assigns it to the Inbound field.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) SetInbound(v []GetLinodeFirewalls200ResponseDataInnerRulesInboundInner) {
	o.Inbound = v
}

// GetInboundPolicy returns the InboundPolicy field value if set, zero value otherwise.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetInboundPolicy() string {
	if o == nil || IsNil(o.InboundPolicy) {
		var ret string
		return ret
	}
	return *o.InboundPolicy
}

// GetInboundPolicyOk returns a tuple with the InboundPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetInboundPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.InboundPolicy) {
		return nil, false
	}
	return o.InboundPolicy, true
}

// HasInboundPolicy returns a boolean if a field has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) HasInboundPolicy() bool {
	if o != nil && !IsNil(o.InboundPolicy) {
		return true
	}

	return false
}

// SetInboundPolicy gets a reference to the given string and assigns it to the InboundPolicy field.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) SetInboundPolicy(v string) {
	o.InboundPolicy = &v
}

// GetOutbound returns the Outbound field value if set, zero value otherwise.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetOutbound() []GetLinodeFirewalls200ResponseDataInnerRulesInboundInner {
	if o == nil || IsNil(o.Outbound) {
		var ret []GetLinodeFirewalls200ResponseDataInnerRulesInboundInner
		return ret
	}
	return o.Outbound
}

// GetOutboundOk returns a tuple with the Outbound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetOutboundOk() ([]GetLinodeFirewalls200ResponseDataInnerRulesInboundInner, bool) {
	if o == nil || IsNil(o.Outbound) {
		return nil, false
	}
	return o.Outbound, true
}

// HasOutbound returns a boolean if a field has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) HasOutbound() bool {
	if o != nil && !IsNil(o.Outbound) {
		return true
	}

	return false
}

// SetOutbound gets a reference to the given []GetLinodeFirewalls200ResponseDataInnerRulesInboundInner and assigns it to the Outbound field.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) SetOutbound(v []GetLinodeFirewalls200ResponseDataInnerRulesInboundInner) {
	o.Outbound = v
}

// GetOutboundPolicy returns the OutboundPolicy field value if set, zero value otherwise.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetOutboundPolicy() string {
	if o == nil || IsNil(o.OutboundPolicy) {
		var ret string
		return ret
	}
	return *o.OutboundPolicy
}

// GetOutboundPolicyOk returns a tuple with the OutboundPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetOutboundPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.OutboundPolicy) {
		return nil, false
	}
	return o.OutboundPolicy, true
}

// HasOutboundPolicy returns a boolean if a field has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) HasOutboundPolicy() bool {
	if o != nil && !IsNil(o.OutboundPolicy) {
		return true
	}

	return false
}

// SetOutboundPolicy gets a reference to the given string and assigns it to the OutboundPolicy field.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) SetOutboundPolicy(v string) {
	o.OutboundPolicy = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetVersion() int32 {
	if o == nil || IsNil(o.Version) {
		var ret int32
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) GetVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given int32 and assigns it to the Version field.
func (o *GetLinodeFirewalls200ResponseDataInnerRules) SetVersion(v int32) {
	o.Version = &v
}

func (o GetLinodeFirewalls200ResponseDataInnerRules) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLinodeFirewalls200ResponseDataInnerRules) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Fingerprint) {
		toSerialize["fingerprint"] = o.Fingerprint
	}
	if !IsNil(o.Inbound) {
		toSerialize["inbound"] = o.Inbound
	}
	if !IsNil(o.InboundPolicy) {
		toSerialize["inbound_policy"] = o.InboundPolicy
	}
	if !IsNil(o.Outbound) {
		toSerialize["outbound"] = o.Outbound
	}
	if !IsNil(o.OutboundPolicy) {
		toSerialize["outbound_policy"] = o.OutboundPolicy
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableGetLinodeFirewalls200ResponseDataInnerRules struct {
	value *GetLinodeFirewalls200ResponseDataInnerRules
	isSet bool
}

func (v NullableGetLinodeFirewalls200ResponseDataInnerRules) Get() *GetLinodeFirewalls200ResponseDataInnerRules {
	return v.value
}

func (v *NullableGetLinodeFirewalls200ResponseDataInnerRules) Set(val *GetLinodeFirewalls200ResponseDataInnerRules) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLinodeFirewalls200ResponseDataInnerRules) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLinodeFirewalls200ResponseDataInnerRules) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLinodeFirewalls200ResponseDataInnerRules(val *GetLinodeFirewalls200ResponseDataInnerRules) *NullableGetLinodeFirewalls200ResponseDataInnerRules {
	return &NullableGetLinodeFirewalls200ResponseDataInnerRules{value: val, isSet: true}
}

func (v NullableGetLinodeFirewalls200ResponseDataInnerRules) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLinodeFirewalls200ResponseDataInnerRules) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


